name: Trigger Netlify Build
on:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
    - name: Request deploy to Netlify
      env:
        NETLIFY_DEPLOY_HOOK: ${{ secrets.NETLIFY_DEPLOY_HOOK }}
      run: curl -X POST -d {} "$NETLIFY_DEPLOY_HOOK"
